### ISSUE TITLE
Order of Chapters

### ISSUE THREAD

**Issue by adamrobinson361** [ukgovdatascience/rap_companion#14]
Few comments from me:

From reading through the book I understand that your definition of RAP is an end to end approach to analytical projects that results in a quality assured push button analytical solution that can be easily re-run and looked back on at any point in time.

This is achieved through the following (in order that they are referenced in the book):

1. Version Control
2. Packaging
3. Unit Testing
4. Dependency Management
5. Some flavour of Markdown, ipython etc. 

This all looks good to me but I'm not sure about the order in which you mention these in the book. 

An order that makes more sense to me and that leads nicely into package development is:

1. What is RAP - give an overview of the sections to come with a short description. 
2. Getting the basics right - creating projects for projects and running multiple scripts from another script. Some sort of folder structure like illustrated [here](https://nicercode.github.io/blog/2013-04-05-projects/). This leads nicely into packaging later on.
3. Markdown, Ipython - how you can easily extend 2. to get end to end analytical solutions by loading scripts from say something like markdown. 
4. Version Control - if you've done all this good work you don't want to lose it. In comes version control.
5. Unit Testing - All analysis needs QA and this is a nice automated way of doing it.
6. Dependency Management - open source packages go out of date. Use something like packrat as you said. 
7. Packages - you can finalise your work by developing it into a package. 

All in all though I think its looking really good and nice to see down in book down format! Could be really good resource once finished!

Feel free to ignore any of my proposals!

Adam

**Comment by mammykins** [comment]
Thanks for this considered reflection; I agree that some extra scaffolding chapters should be put in and I like the idea of getting the basics right or the bare minimum features that a project should have in place. 

Would you @adamrobinson361 like to collaborate and take one of these suggestions on which could be used to evidence an objective of building data science capability across departments? e.g. the folder structure of a project

**Comment by adamrobinson361** [comment]
Sounds like a good idea to collaborate on this. I'm by no means an expert but can use my knowledge and some research to put something together on projects and folder structures, sourcing r scripts etc

**Comment by mammykins** [comment]
It's great if we can have different levels of support for the variety of users that may be attempting to implement some RAP principles in the future. Thus any learnings you have will be invaluable and we can use crowd feedback to iterate as appropriate.
