### ISSUE TITLE
Fix page title

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ukgovdatascience/rap_companion#16]
When I load the page, I get the page url returned and bizarrely crossed through with a grey line. 

<img width="463" alt="screen shot 2017-07-18 at 11 49 47" src="https://user-images.githubusercontent.com/4583655/28313600-5f29e90c-6baf-11e7-8488-4801542de3eb.png">

**Comment by mammykins** [comment]
Thanks. I think that's a faulty book cover page.

**Comment by mammykins** [comment]
It was due to the 
url: ...
in the yaml of the index.Rmd
