### ISSUE TITLE
Recommended packages

### ISSUE THREAD

**Issue by vickyhughes** [ukgovdatascience/rap_companion#36]
Have been thinking it could be worth a section on recommended packages to use for certain things, e.g. to produce tables in Markdown the Government recommendation is.. kable, for example. It would be ideal to have consistency across Departments where suitable, especially considering how frequently statisticians move roles.

**Comment by ivyleavedtoadflax** [comment]
Sounds like a plan. Can you be tempted into making a start?

**Comment by mammykins** [comment]
That's a good idea @vickyhughes, check out the CONTRIBUTING.md

**Comment by vickyhughes** [comment]
Will do both - next week!

**Comment by mammykins** [comment]
Shall we close on completion?

**Comment by mammykins** [comment]
https://ukgovdatascience.github.io/rap_companion/final.html#a-structured-rap-course
Closed by #48 
This links to Awesome R packages
