### ISSUE TITLE
Getting to the data store stage

### ISSUE THREAD

**Issue by stevedempseybis** [ukgovdatascience/rap_companion#53]
One of the big issue for stats is that the data store is actually often a loosely connected and poorly designed bunch of spreadsheets, with none of the integrity that you'd expect, or require, to build the RAP.

Sorting out this issue is a significant blocker to the development of an RAP. 

I wondered if you'd considered working backwards from the point at which the current RAP companion starts to give advice and guidance on persuading statisticians that creating proper data storage is a worthwhile effort, and how the build might be approached.

**Comment by mammykins** [comment]
Great insight and I agree, a quality data store is key.

The DCMS eesectors package starts from a position of a few spreadsheets and SPSS files, we've added some fake example spreadsheets to demonstrate this (see the inst directory), which are read in by the extract family of functions. This data is held in a bespoke S3 class in R to make life easier for the user. We should endeavour to clarify these steps in the companion.

This expansion of detail for this step could fit in here:
https://ukgovdatascience.github.io/rap_companion/exemplar.html#tidy-data

@maxwell8888 is the expert and can perhaps provide greater insight.

In terms of writing a case for improving the quality of data and how its stored that goes beyond the remit of what I had in mind.
