### ISSUE TITLE
Rather than minimal tidy data, consider tibble cube?

### ISSUE THREAD

**Issue by mammykins** [ukgovdatascience/rap_companion#56]

**Comment by nacnudus** [comment]
@mammykins can you provide any more detail about this?  Is it about [`dplyr::tbl_cube()`](https://dplyr.tidyverse.org/reference/tbl_cube.html)?

**Comment by nacnudus** [comment]
Closing because `dplyr::tbl_cube()` is still documented as 'experimental' and doesn't seem to be used much if at all.  Perhaps the tidyverse developers will return to this idea one day.
