### ISSUE TITLE
guidance on what license to choose for open source projects

### ISSUE THREAD

**Issue by maxwell8888** [ukgovdatascience/rap_companion#62]
I think this would be helpful to include some guidance in the companion. For example, eesectors is a public github repo with no license.

**Comment by mammykins** [comment]
Could reference the service manual: https://www.gov.uk/service-manual/technology/making-source-code-open-and-reusable#licensing-your-code

**Comment by maxwell8888** [comment]
nice, yeah I didn't realise that existed!
