### ISSUE TITLE
Citations needed

### ISSUE THREAD

**Issue by nacnudus** [ukgovdatascience/rap_companion#79]
* [Research on spreadsheet errors is substantial, compelling, and unanimous](https://ukgovdatascience.github.io/rap_companion/why.html#why-learning-to-rap-might-be-hard)
* Add any others here

**Comment by matt-dray** [comment]
Not 'research', but to address [that particular footnote](https://ukgovdatascience.github.io/rap_companion/why.html#why-learning-to-rap-might-be-hard):
* https://www.bloomberg.com/news/articles/2013-04-18/faq-reinhart-rogoff-and-the-excel-error-that-changed-history
* http://panko.shidler.hawaii.edu/SSR/Mypapers/whatknow.htm
* https://www.cio.com/article/2438188/enterprise-software/eight-of-the-worst-spreadsheet-blunders.html

**Comment by mammykins** [comment]
See my blog, they're probably in there:
https://www.machinegurning.com/rstats/spreadsheet_classification/

**Comment by nacnudus** [comment]
Thanks both for the links.  I've [added them](https://github.com/ukgovdatascience/rap-website/commit/290c173e34cb4b9798806afa097a3a1afc9538ef) to the [RAP Website edition](https://ukgovdatascience.github.io/rap-website/rap-companion-03-why.html) of the companion.  Once again packrat hasn't enabled me to build the original bookdown, so for a relatively minor change like this I'm just going to leave it be.
