### ISSUE TITLE
RAP infrastructure

### ISSUE THREAD

**Issue by sebastian-fox** [ukgovdatascience/rap_companion#84]
Hi @nacnudus,

I think a chapter bringing all the infrastructure required for RAP would be useful. It might be a little challenging because software/hardware is changing rapidly and everyone is starting from a different place, but some guidance on infrastructure would help those that are starting on the RAP journey but don't have the full knowledge of what's required. As usual, investing in new software/hardware is quite difficult if you don't quite know what you want it for or even whether it does what you need. 

To keep this all together, some thoughts you described to me are:

> RAP is technology agnostic so it might suggest GitLab, RStudio etc. as examples of version control and IDEs.  To your list I would add some softer things that are well worth getting at the same time, such as access to Slack and Google Drive for collaborating outside PHE -- perhaps that isn't a problem for you.  For the RAP companion I would add things like access to GitHub through any proxies, RTools to compile certain packages, and something for disseminating documents e.g. RStudioConnect.

My thoughts for PHE were:
* Git software (we already have it and are using it)
* GitLab (internal code) and GitHub (external code)
* A server for Continuous Integration (we don’t currently have this set up for GitLab) and code coverage
* An internal miniCRAN store for package management (we use both internally developed packages and regular CRAN packages)
* RStudio Server – this will have the benefits for new R users so that they don’t get caught out by old package versions (we all work off Desktop currently); I’d be keen to hear your thoughts on this

Thanks,
Seb

**Comment by nacnudus** [comment]
@sebastian-fox Thank you for writing this issue.  Sorry it has taken so long to get around to it.  I have added an [article](https://ukgovdatascience.github.io/rap-website/article-infrastructure.html) to the RAP website, and I would be grateful if you could review it and suggest changes in a new issue or a pull request.
