### ISSUE TITLE
How to win users and influence statistical production

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/rap_companion#85]
A section with tools to convince people they need RAP.

I'm thinking business case stuff, testimonials (particularly to replace [the placeholder quote in 2.1.1](https://ukgovdatascience.github.io/rap_companion/ethics.html)), proof of time savings, etc.

Also could include a 'RAP as reform' approach. The process of RAP can help _improve_ content, not just replicate what's already produced. For example, do some user research as part of the process. (This is needed particularly for Excel spreadsheets that come bundled with the release – speak to @lauraselby and co.)

**Comment by matt-dray** [comment]
Relevant xkcd: https://xkcd.com/1205/

But: https://xkcd.com/1319/

**Comment by nacnudus** [comment]
Lots of this is now covered by the [case study](https://ukgovdatascience.github.io/rap-website/resource-case-study-benefits-2017.html).

**Comment by matt-dray** [comment]
Agree. Happy to close and look forward to the articles section expanding.
