### ISSUE TITLE
Expand dependencies chapter

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/rap_companion#89]
[The chapter is just a placeholder currently](https://ukgovdatascience.github.io/rap_companion/dep.html).

Things to do:

* Highlight possible tools: `sessionInfo`, `packrat`, `checkpoint` (all R), `virtualenv` and others (Python) and Docker (including R flavours)
* Proposed 'tiers' of good dependency management, e.g. for R: nothing < `sessionInfo` only < `packrat` only < `Docker` + `packrat`, etc
* Focus on Docker as an ideal solution (as per #78 'add docker example')
* Hurdles when using some of these approaches (e.g. IT barriers, knowledge barriers, conceptual barriers)
* Examples of dependency management other RAP publications (e.g. [eesectors uses `packrat`](https://github.com/DCMSstats/eesectors))
* Consider commentary in #86 ('Packrat is more trouble than it's worth: discuss')

**Comment by nacnudus** [comment]
This looks good for reproducibility.  Dependency is a broader topic though, so maybe this should be "Dependencies and reproducibility" with a separate section "Dependencies and reusability" that prioritises ease of reuse, ease of maintenance and upgrading, patching, versioning, deprecation, etc.

**Comment by nacnudus** [comment]
@AoifeONeill I'm sure @matt-dray would gladly share his first draft with you.  Google Docs is probably better for this kind of review than github.

**Comment by nacnudus** [comment]
Another few packages:
* https://github.com/MangoTheCat/pkgsnap/issues via the [Data Science Campus](https://datasciencecampus.github.io/coding-standards/r.html#deps-r)
* https://github.com/cole-brokamp/automagic
* [GRAN and switchr](https://blog.revolutionanalytics.com/2014/08/gran-and-switchr-cant-send-you-back-in-time-but-they-can-send-r-sort-of.html)

Hadley's advice about surprise breaking changes: [commit the rendered .Rmd](https://twitter.com/frod_san/status/847085478469947392)

**Comment by matt-dray** [comment]
I'm going to close this, given #97 

The chapter has definitely _expanded_, but is not 'complete' (in the sense that all of these chapters will continue to be iterated upon).
