### ISSUE TITLE
RAP website rather than just a bookdown endpoint

### ISSUE THREAD

**Issue by nacnudus** [ukgovdatascience/rap_companion#92]
So we can publish articles, blog posts, other content.

**Comment by matt-dray** [comment]
Are you thinking Blogdown + Netlify?

PaaS, maybe?

**Comment by nacnudus** [comment]
I'm thinking maybe something like [this](https://ukgovdatascience.github.io/rap-website/index.html) ([GitHub](https://github.com/ukgovdatascience/rap-website)).
