### ISSUE TITLE
Acknowledge contributions to RAP Companion

### ISSUE THREAD

**Issue by matt-dray** [ukgovdatascience/rap_companion#96]
We can capture contributors via GitHub: https://github.com/ukgovdatascience/rap_companion/graphs/contributors

What about contributors who haven't contributed code? 

This could be in an acknowledgements section, perhaps in the preface.

**Comment by nacnudus** [comment]
+1 for acknowledgements in the preface

**Comment by nacnudus** [comment]
Now that the companion is frozen and your contribution will be a standalone page on the RAP Website, does that change this?  We could ask the community how they feel about being named.  There's also a PII aspect to this.

**Comment by matt-dray** [comment]
Correct. This issue is unnecessary now. People can just look at the commits for authors if they really want. Especially given that adapted content and contributions from non-GitHub-users haven't been included (as far as I know). Closing it.
